### PR TITLE
Cleanup crew 2

### PR DESCRIPTION
**Pull request by MaxOliveberg**
Sorterade lite i er shitcode no biggie

kanske fuckade upp git men de är nog lugnt. klicka på merge för att förbättra er kod

edit: ha hela projekten i gitten i separata folders, inte bara folders med .javas, annars är de svårt att operera på.

### CODE REVIEW

**Comment by MaxOliveberg** [comment]
Merge this asap @haggren

**Comment by haggren** [comment]
Hello @MaxOliveberg i have taken a look at your pull request and have decided that it will not be merged. Thank you and good day.

Best regards, Hugo Haggren

**Comment by MaxOliveberg** [comment]
Hello @haggren, thanks for your quick and timely response.

I've been looking at your code and commit history, and your project has some serious potential. However, it is quite apparent that you lack Github-expertise. I'd be willing to come into your project as an executive collaborator and auxiliary coder. My resume is both long, and impressive, with many merged PRs on many different, high profile Gits. Please reach out to me at gitlordmax@su.se.

Best regards, 

Max Oliveberg

**Comment by haggren** [comment]
Hi again @MaxOliveberg.

Sorry for not getting back to you immediately. I had to talk a few things over with my colleague, Johan "java-Johan" Ericsson. First of all, we appreciate your kind words and we agree that there are improvements that could be made in the Github-area of this project. With that being said I would personally like to offer you a position with us. You would be working as a full time Git-Boy with a monthly pay that is up to market standards. 

I hope this proposition is something that interests you.

Best regards,
Hugo Haggren, CEO

**Comment by MaxOliveberg** [comment]
Hell yeah dude, give me collaborator status and I'll get to work.
Cheers, Max

**Comment by MaxOliveberg** [comment]
conflicts, i am closing this pr as the project has moved past this point.

**Pull request closed without merging**
